development:
  access_key_id: "AKIAJUERKL7GKE4UEJ3A"
  secret_access_key: "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"

production:
  access_key_id: "AKIAJUERKL7GKE4UEJ3A"
  secret_access_key: "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"